name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2

      - name: Create the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: release/github_action/dist/index.js
